# Generated by Django 4.2.16 on 2026-06-24 00:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_enable_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('partial', 'partial'), ('failed', 'failed')], default='failed', max_length=20)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('address', models.TextField(blank=True, default='')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('main_reason', models.CharField(blank=True, default='', max_length=255)),
                ('police_action', models.BooleanField(default=False)),
                ('agent_presence', models.BooleanField(default=False)),
                ('fatalities', models.PositiveIntegerField(default=0)),
                ('injuries', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('raw', models.JSONField(default=dict)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Occurrence',
                'verbose_name_plural': 'Occurrences',
                'indexes': [models.Index(fields=['city'], name='api_occurre_city_1fd78d_idx'), models.Index(fields=['main_reason'], name='api_occurre_main_re_bc55da_idx'), models.Index(fields=['neighborhood'], name='api_occurre_neighbo_a5d1ad_idx')],
            },
        ),
    ]
