# Generated by Django 5.0.1 on 2024-01-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogo_cruzado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='context_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='victims',
            field=models.TextField(blank=True, null=True),
        ),
    ]
