# Generated by Django 5.0.1 on 2024-01-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogo_cruzado', '0002_occurrence_context_info_occurrence_victims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='context_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='victims',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
