# Generated by Django 5.0.1 on 2024-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogo_cruzado', '0003_alter_occurrence_context_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='context_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='victims',
            field=models.TextField(blank=True, null=True),
        ),
    ]
