# Generated by Django 5.0.1 on 2024-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogo_cruzado', '0005_occurrence_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='neighborhood',
            field=models.TextField(blank=True, null=True),
        ),
    ]
