# Generated by Django 5.0.1 on 2024-01-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogo_cruzado', '0006_occurrence_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
